# Generated by Django 3.1 on 2021-10-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211020_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Product Translation'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Review Rating', 'verbose_name_plural': 'Review Ratings'},
        ),
    ]
