# Generated by Django 3.1 on 2021-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211121_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='In Hand'),
        ),
    ]
