# Generated by Django 3.1 on 2021-11-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20211123_0908'),
        ('store', '0006_product_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='confirmation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='In Hand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Old Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Short Description'),
        ),
    ]
