# Generated by Django 3.1 on 2021-11-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211123_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Name'),
        ),
    ]
