# Generated by Django 3.1 on 2022-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20211021_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IP'),
        ),
    ]
