# Generated by Django 3.1 on 2022-12-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
