# Generated by Django 3.1 on 2021-10-20 12:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='abouttranslation',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(upload_to='images/banners', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, max_length=155, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='menutranslation',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='store/partners', verbose_name='Image'),
        ),
    ]
